application: joerowley111
version: 1
runtime: python
api_version: 1

handlers:
- url: .*
  script: django_bootstrap.py

- url: /game
  static_files: statics/gameoflife.html
  upload: statics/gameoflife.html